### ISSUE TITLE
The AWK script might not be portable?

### ISSUE THREAD

**Issue by hugomg** [pallene-lang/lua-internals#1]
https://github.com/pallene-lang/pallene/issues/516#issuecomment-1648683107

- BEGINFILE might be a GNU-ism
- Somehow it's including itself in the generated luacore.h?

**Comment by hugomg** [comment]
@Nomarian, could you please tell us more about what system you're using? Is it not GNU Awk?

I'm not sure it would be the best idea to switch this to a Lua script, because needing Lua to build the custom Lua is a bit of a chicken-egg problem. Perhaps it would be simpler to provide tarballs that already contain the generated luacore.h? Is there an easy/automated way to do that on Github?

**Comment by Nomarian** [comment]
The solution is changing BEGINFILE to FNR==1, I've attached a diff on some other changes.


[luacore.diff.txt](https://github.com/pallene-lang/lua-internals/files/12153108/luacore.diff.txt)


I'm also a bit worried about get-lua-core-h.awk being mentioned twice in the make output.


```
awk -f gen-lua-core-h.awk gen-lua-core-h.awk llimits.h lctype.h lopcodes.h lmem.h lobject.h lzio.h ltable.h lfunc.h ltm.h lparser.h llex.h lundump.h lstate.h lcode.h ldebug.h lapi.h ldo.h lgc.h lvm.h lstring.h > luacore.h  
```


I should mention, pallene builds succesfully, its only when you { pallenenc script.pln } that it fails. even when you --emit-c

**Comment by Nomarian** [comment]
perhaps using a lua script is a no, considering building pallene when you already have lua installed is slightly more complicated (luarocks does not accept --with-lua correctly but that's another matter)

**Comment by Nomarian** [comment]
[POSIX awk spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html)


FWIW, BEGINFILE only exists in gawk, not even busybox awk or goawk have it.

**Comment by hugomg** [comment]
Does changing to FNR==1 fix that failure you're having?

> I'm also a bit worried about get-lua-core-h.awk being mentioned twice in the make output.

Basically, we want to tell make to regenerate luacore.h if either the AWK script or any of the core headers change. Furthermore, the script wants to receive the list of core header files. Currently we're passing the whole `$^` which includes the headers plus the awk script itself (which we then try to skip with that broken if_header check). Ideally we'd tell the makefile to only pass the header files to the generator script, but  I didn't know how to do that portable make. Any ideas?

**Comment by hugomg** [comment]
I had an idea... @Nomarian, could you please check if that PR helps?

**Comment by Nomarian** [comment]
Works, and its even better than using FNR==1
